/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_AnotherTest */

#ifndef _Included_com_example_hellojni_AnotherTest
#define _Included_com_example_hellojni_AnotherTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_AnotherTest
 * Method:    GetWater
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_AnotherTest_GetWater
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hellojni_AnotherTest
 * Method:    GetBasicTypes
 * Signature: (Z[BCIJFD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_AnotherTest_GetBasicTypes
  (JNIEnv *, jobject, jboolean, jbyteArray, jchar, jint, jlong, jfloat, jdouble);

#ifdef __cplusplus
}
#endif
#endif
